### PR TITLE
Cranelift: Fix FPR saving and shadow space allocation for Windows x64.

### LINKED ISSUE #1475: Cranelift: refactor Windows stack layout for unwind constraints
Cranelift should be able to compile x86 functions with stack frames requiring 240 bytes or more, when that also requires preserving a SIMD register. We've had to track an extension to the fastcall ABI that requires saving some, and due to Cranelift's choice in stack layout for these functions it's impossible to satisfy constraints required by Windows unwind information.

#### Benefit

Cranelift and its users can have unwind information for these functions.

#### Implementation

I _think_ what we'll want to do is move the location FPRs are preserved in up before stack locals, so they have small offsets from the function's stack frame base. See the diagram in @peterhuene's comment [here](https://github.com/bytecodealliance/wasmtime/pull/1216#discussion_r387409892) and associated conversation for more.

#### Alternatives

Cranelift and its users don't have unwind information for some functions (currently witnessed as a panic, so users can't opt out for problematic functions)

ed: currently we miscompile these functions with or without unwind information. After https://github.com/bytecodealliance/wasmtime/pull/1216 lands, we'll produce working code, but not unwind information, for these. Specifically, unwind information for functions that would require these out-of-range FPR save offsets.

### LINKED ISSUE #1587: Rust doesn't work by default on Windows
I ran across this uptream in cargo-wasi, but this fails to work in this repository, but only on Windows:

```
$ echo "#[test] fn foo() {}" >> foo.rs
$ rustc foo.rs --target wasm32-wasi --test
$ cargo run foo.wasm
    Finished dev [unoptimized + debuginfo] target(s) in 0.28s
     Running `target\debug\wasmtime.exe foo.wasm`
Error: failed to run main module `foo.wasm`

Caused by:
    0: WebAssembly failed to compile
    1: Compilation error: Implementation limit exceeded
```

The underlying reason can be found with `RUST_LOG`:

```
$ RUST_LOG=warn cargo run foo.wasm
    Finished dev [unoptimized + debuginfo] target(s) in 0.25s
     Running `target\debug\wasmtime.exe foo.wasm`
 WARN  cranelift_codegen::isa::x86::unwind::winx64 > stack frame is too large (288 bytes) to use with Windows x64 SEH when preserving FPRs. This is a Cranelift implementation lim
it, see https://github.com/bytecodealliance/wasmtime/issues/1475
 WARN  cranelift_codegen::isa::x86::unwind::winx64 > stack frame is too large (416 bytes) to use with Windows x64 SEH when preserving FPRs. This is a Cranelift implementation lim
it, see https://github.com/bytecodealliance/wasmtime/issues/1475
Error: failed to run main module `foo.wasm`

Caused by:
    0: WebAssembly failed to compile
    1: Compilation error: Implementation limit exceeded
error: process didn't exit successfully: `target\debug\wasmtime.exe foo.wasm` (exit code: 1)
```

It looks like it's due to [these lines](https://github.com/bytecodealliance/wasmtime/blob/4736a1c5774d6641af4d920a265ae3fe91c85ee8/cranelift/codegen/src/isa/x86/unwind/winx64.rs#L187-L193) introduced in https://github.com/bytecodealliance/wasmtime/pull/1216. cc @iximeow do you know how hard it'd be to fix that warning?

### LINKED ISSUE #1728: Cranelift: improper handling of shadow store for winx64 calling convention
- What are the steps to reproduce the issue? Can you include a CLIF test case,
  ideally reduced with the `bugpoint` clif-util command?

`repro.clif`:

```clif
set opt_level=speed_and_size
set is_pic
target x86_64 haswell

function %foo() windows_fastcall {
    fn0 = %bar(i64)
    ss0 = explicit_slot 8
block0:
    v1 = stack_addr.i64 ss0
    call fn0(v1)
    return
}
```

```
$ clif-util compile -D repro.clif
```

- What do you expect to happen? What does actually happen? Does it panic, and
  if so, with which assertion?

Actual output:

```
.byte 85, 72, 137, 229, 87, 72, 131, 236, 40, 72, 141, 132, 36, 0, 0, 0, 0, 72, 137, 199, 232, 0, 0, 0, 0, 72, 131, 196, 40, 95, 93, 195

Disassembly of 32 bytes:
   0:   55                      push    rbp
   1:   48 89 e5                mov     rbp, rsp
   4:   57                      push    rdi
   5:   48 83 ec 28             sub     rsp, 0x28
   9:   48 8d 84 24 00 00 00 00 lea     rax, [rsp]
  11:   48 89 c7                mov     rdi, rax
  14:   e8 00 00 00 00          call    0x19
  19:   48 83 c4 28             add     rsp, 0x28
  1d:   5f                      pop     rdi
  1e:   5d                      pop     rbp
  1f:   c3                      ret
```

Note the instruction at **offset 9** that is loading the address of the explicit stack slot: `lea rax, [rsp]`.  The address loaded is actually *inside* the callee's 32 bytes of shadow space. 

I expect this instruction to actually account for the calling convention's shadow space: `lea rax, [rsp+0x20]`.

Because of how we're currently saving callee-saved FPRs, we're actually saving the FPRs into this area of the stack as well, meaning that the callee might trash the caller's saved FPRs as they're allowed to use this space freely.

Because Cranelift itself doesn't make use of the caller-provided shadow space, this won't happen for Cranelift-to-Cranelift calls; however, calling into external functions will certainly make use of the shadow space.

- Which Cranelift version / commit hash / branch are you using?

26e06297957bbc06b3244bc96d2e92b4246e8d9b

- If relevant, can you include some extra information about your environment?
  (Rust version, operating system, architecture...)

Rust: 1.43.1
Operating system: Arch Linux
Arch: x86-64

### PR DESCRIPTION
**Pull request by peterhuene**
This PR fixes both how FPR callee-saved registers are saved and how the
shadow space allocation occurs when laying out the stack for Windows x64
calling convention.

Importantly, this PR removes the compiler limitation of stack size for
Windows x64 that was imposed because FPR saves previously couldn't always be
represented in the unwind information.

The FPR saves are now performed without using stack slots, much like how the
callee-saved GPRs are saved. The total CSR space is given to `layout_stack` so
that it is included in the frame size and to offset the layout of spills and
explicit slots.

The FPR saves are now done via an RSP offset (post adjustment) and they always
follow the GPR saves on the stack. A simpler calculation can now be made to
determine the proper offsets of the FPR saves for representing the unwind
information.

Additionally, the shadow space is no longer treated as an incoming argument,
but an explicit stack slot that gets laid out at the lowest address possible in
the local frame. This prevents `layout_stack` from putting a spill or explicit
slot in this reserved space. In the future, `layout_stack` should take
advantage of the *caller-provided* shadow space for spills, but this PR does
not attempt to address that.

The shadow space is now omitted from the local frame for leaf functions.

Fixes #1728.
Fixes #1587.
Fixes #1475.

### CODE REVIEW

**Comment by peterhuene** [comment]
See [this comment](https://github.com/bytecodealliance/wasmtime/issues/1587#issuecomment-631356885) for a "before and after" codegen.

File: cranelift/codegen/src/isa/x86/abi.rs [hunk 1]
```diff
@@ -525,50 +523,60 @@ fn fastcall_prologue_epilogue(func: &mut ir::Function, isa: &dyn TargetIsa) -> C
...
-            kind: ir::StackSlotKind::ExplicitSlot,
-            size: (num_fprs * types::F64X2.bytes() as usize) as u32,
-            offset: None,
-        }))
-    } else {
-        None
-    };
+    // FPRs must be saved with 16-byte alignment; because they follow the GPRs on the stack, align if needed
+    if fpsr_stack_size > 0 {
+        csr_stack_size += gpsr_stack_size & isa.pointer_bytes() as u32;
```
Comment (iximeow) [inline cranelift/codegen/src/isa/x86/abi.rs:540]: To be correct for cases where `isa.pointer_bytes() != 8`:
```suggestion
        csr_stack_size = (csr_stack_size + 15) & !15;
```

File: cranelift/codegen/src/isa/x86/abi.rs [hunk 2]
```diff
@@ -799,38 +826,27 @@ fn insert_common_prologue(
...
+        pos.func.locations[csr_arg] = ir::ValueLoc::Reg(reg);
 
-            last_fpr_save =
-                Some(
-                    pos.ins()
-                        .store(ir::MemFlags::trusted(), csr_arg, stack_addr, fpr_offset),
-                );
+        // Offset to where the register is saved relative to RSP, accounting for FPR save alignment
+        let offset = ((i + 1) * types::F64X2.bytes() as usize) as i64
+            + (stack_size & isa.pointer_bytes() as i64);
```
Comment (iximeow) [inline cranelift/codegen/src/isa/x86/abi.rs:842]: since `local_stack_size` ought to be 16-byte aligned, shouldn't `stack_size & isa.pointer_bytes()` always be zero? It seems like we could lift this up to an assert on function entry, if so.

File: cranelift/codegen/src/isa/x86/unwind/winx64.rs [hunk 3]
```diff
@@ -183,41 +136,41 @@ pub(crate) fn create_unwind_info(
...
-    // no preserved FPRs, we can lie without error and claim the offset to RBP is 0 - nothing
-    // will actually check it. This, then, avoids panics when compiling functions with large
-    // call frames.
-    let reported_frame_offset = if saved_fpr {
-        (static_frame_allocation_size / 16) as u8
-    } else {
-        0
-    };
+        // Account for alignment space when there's an odd number of GPR pushes
+        frame_register_offset = fpr_save_count + ((gpr_push_count + 1) / 2);
```
Comment (iximeow) [inline cranelift/codegen/src/isa/x86/unwind/winx64.rs:166]: Being `winx64.rs`, I think the assumption that a GPR is half the size of an FPR is workable, but do you think that's worth noting in this comment?

File: cranelift/filetests/filetests/isa/x86/windows_fastcall_x64.clif [hunk 4]
```diff
@@ -8,29 +8,57 @@ function %one_arg(i64) windows_fastcall {
 block0(v0: i64):
     return
 }
-; check: function %one_arg(i64 [%rcx], i64 fp [%rbp]) -> i64 fp [%rbp] windows_fastcall {
-; nextln: ss0 = incoming_arg 16, offset -48
+; check:  function %one_arg(i64 [%rcx], i64 fp [%rbp]) -> i64 fp [%rbp] windows_fastcall {
+; nextln: ss0 = incoming_arg 16, offset -16
+; check:  block0(v0: i64 [%rcx], v1: i64 [%rbp]):
```
Comment (iximeow) [inline cranelift/filetests/filetests/isa/x86/windows_fastcall_x64.clif:13]: Any particular reason to check the rest of the function? Seems independent of making sure there's an `ss0` and that this compiles.

File: cranelift/filetests/filetests/isa/x86/windows_fastcall_x64.clif [hunk 5]
```diff
@@ -8,29 +8,57 @@ function %one_arg(i64) windows_fastcall {
...
 
 ; check if we still use registers for 4 arguments
 function %four_args(i64, i64, i64, i64) windows_fastcall {
 block0(v0: i64, v1: i64, v2: i64, v3: i64):
     return
 }
-; check: function %four_args(i64 [%rcx], i64 [%rdx], i64 [%r8], i64 [%r9], i64 fp [%rbp]) -> i64 fp [%rbp] windows_fastcall {
+; check:  function %four_args(i64 [%rcx], i64 [%rdx], i64 [%r8], i64 [%r9], i64 fp [%rbp]) -> i64 fp [%rbp] windows_fastcall {
+; nextln: ss0 = incoming_arg 16, offset -16
+; check:  block0(v0: i64 [%rcx], v1: i64 [%rdx], v2: i64 [%r8], v3: i64 [%r9], v4: i64 [%rbp]):
```
Comment (iximeow) [inline cranelift/filetests/filetests/isa/x86/windows_fastcall_x64.clif:27]: Likewise, I'm not sure what the checks on this function body are intending to test past the `ss0` line?

File: cranelift/filetests/filetests/isa/x86/windows_fastcall_x64.clif [hunk 6]
```diff
@@ -94,3 +135,100 @@ block0(v0: i64):
     store.i64 v9, v0+72
     return v10
 }
+; check:  function %internal_stack_a(i64 [%rcx], i64 fp [%rbp], i64 csr [%r12], i64 csr [%r13], i64 csr [%r14], i64 csr [%r15]) -> i64 [%rax], i64 fp [%rbp], i64 csr [%r12], i64 csr [%r13], i64 csr [%r14], i64 csr [%r15] windows_fastcall {
```
Comment (iximeow) [inline cranelift/filetests/filetests/isa/x86/windows_fastcall_x64.clif:138]: :tada: :tada:

File: cranelift/codegen/src/isa/x86/abi.rs (hunk 2 above)
Comment (peterhuene) [reply cranelift/codegen/src/isa/x86/abi.rs:842]: `stack_size` (i.e. the adjustment to RSP) is not 16-byte aligned as it might be aligning RSP back to a 16-byte alignment.

Take for instance a prologue in a non-leaf function that pushes the frame pointer and then saves a single GPR.  The push of the frame pointer realigned the stack from the push of return address, but the push of the GPR causes a misalignment.  The local stack allocation will be +0x8 to account for that, which means `stack_size` itself is not a multiple of 16, but 8.

This lines cause causes the offset to be +0x8 when `stack_size` itself is +0x8 so that it gets subtracted out from the final offset from the post-adjusted RSP.  The end result is that the offset should always be a multiple of 16 from a post-adjusted 16-byte aligned RSP.

Comment (peterhuene) [reply cranelift/codegen/src/isa/x86/abi.rs:842]: That said, I'm totally open to calculating this in a clearer way if you have any suggestions!

File: cranelift/codegen/src/isa/x86/abi.rs (hunk 1 above)
Comment (peterhuene) [reply cranelift/codegen/src/isa/x86/abi.rs:540]: I think that's clearer and congruent with other places where we round up for alignment.  I'll change.

File: cranelift/codegen/src/isa/x86/unwind/winx64.rs (hunk 3 above)
Comment (peterhuene) [reply cranelift/codegen/src/isa/x86/unwind/winx64.rs:166]: I can add a comment.

File: cranelift/filetests/filetests/isa/x86/windows_fastcall_x64.clif (hunk 4 above)
Comment (peterhuene) [reply cranelift/filetests/filetests/isa/x86/windows_fastcall_x64.clif:13]: I wanted to check the prologues and epilogues for correctness in each function.  The intermediate instructions I'm not as concerned about, although I personally don't mind them being checked unless we think there's a likelihood that this will cause a maintenance headache for these tests.

File: cranelift/filetests/filetests/isa/x86/windows_fastcall_x64.clif (hunk 5 above)
Comment (peterhuene) [reply cranelift/filetests/filetests/isa/x86/windows_fastcall_x64.clif:27]: See reply above.  Do you think it would be best if we simply limited it to just the stack layout and prologue/epilogue instructions?

File: cranelift/filetests/filetests/isa/x86/windows_fastcall_x64.clif (hunk 6 above)
Comment (peterhuene) [reply cranelift/filetests/filetests/isa/x86/windows_fastcall_x64.clif:138]: It turns out asserting things in tests is good :smile:.

File: cranelift/codegen/src/isa/x86/abi.rs (hunk 2 above)
Comment (iximeow) [reply cranelift/codegen/src/isa/x86/abi.rs:842]: That example helps, thanks. How's `% types::F64X2.bytes()` instead of `& isa.pointer_bytes()` sound to you? That picks an aligned offset for the type to store, ought to work for `isa.pointer_bytes() == 4`, and makes extension for ymm preservation (if we get to that in the future) clearer (they don't _need_ 32-byte alignment, but iiuc are somewhat penalized for misaligned access)

File: cranelift/filetests/filetests/isa/x86/windows_fastcall_x64.clif (hunk 4 above)
Comment (iximeow) [reply cranelift/filetests/filetests/isa/x86/windows_fastcall_x64.clif:13]: Yeah I'm just thinking of maintenance for these. But I've convinced myself it's actually good to extend these checks here: I don't think we explicitly tested fastcall gpr preservation works as expected anywhere, and these aren't really liable to change in a surprising way.

File: cranelift/filetests/filetests/isa/x86/windows_fastcall_x64.clif (hunk 5 above)
Comment (iximeow) [reply cranelift/filetests/filetests/isa/x86/windows_fastcall_x64.clif:27]: (as above, now convinced that these are Good Actually)

File: cranelift/codegen/src/isa/x86/abi.rs (hunk 2 above)
Comment (peterhuene) [reply cranelift/codegen/src/isa/x86/abi.rs:842]: Works for me.  I'll get that changed!

**Comment by alexcrichton** [comment]
I think that this may be all that's necessary to [remove this ignore block](https://github.com/bytecodealliance/wasmtime/blob/26ee986c2f99bb339f171267731f9108890044ab/build.rs#L209-L219) as well perhaps?

**Comment by peterhuene** [comment]
Good catch!  I forgot we had disabled tests because of this issue.  I'll re-enable.

File: cranelift/codegen/src/isa/x86/unwind/winx64.rs [hunk 7]
```diff
@@ -183,41 +136,42 @@ pub(crate) fn create_unwind_info(
...
 
-    if saved_fpr {
-        if static_frame_allocation_size > 240 && saved_fpr {
-            warn!("stack frame is too large ({} bytes) to use with Windows x64 SEH when preserving FPRs. \
-                This is a Cranelift implementation limit, see \
-                https://github.com/bytecodealliance/wasmtime/issues/1475",
-                static_frame_allocation_size);
-            return Err(CodegenError::ImplLimitExceeded);
+    let mut frame_register_offset = 0;
+    if xmm_save_count > 0 {
```
Comment (peterhuene) [inline cranelift/codegen/src/isa/x86/unwind/winx64.rs:140]: This should actually check if a frame pointer is being used, even though we currently always use one.

If a frame pointer is not used, then the offsets for the FPRs saves should not be altered as they already have the correct offset from RSP.

I'll quickly fix this.

**Comment by peterhuene** [comment]
@bnjbvr would you mind reviewing or suggesting a reviewer from cranelift core?  Thanks!

**Comment by peterhuene** [comment]
After discussing with Dan, I'm proceeding with merging this with @iximeow's sign-off.

**Comment by bnjbvr** [comment]
Oops, sorry I didn't see this among the github-bot mentions; I entirely trust @iximeow's reviews when it comes to Cranelift, for what it's worth :)
