### PR TITLE
Fix usage of default_libcall_names

### PR DESCRIPTION
**Pull request by bjorn3**
```
error[E0308]: mismatched types
   --> src/backend.rs:198:9
    |
198 |         cranelift_module::default_libcall_names(),
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected trait `std::ops::Fn(cranelift_codegen::ir::LibCall) -> std::string::String + std::marker::Send + std::marker::Sync`, found trait `std::ops::Fn(cranelift_codegen::ir::LibCall) -> std::string::String`
    |
    = note: expected struct `std::boxed::Box<(dyn std::ops::Fn(cranelift_codegen::ir::LibCall) -> std::string::String + std::marker::Send + std::marker::Sync + 'static)>`
               found struct `std::boxed::Box<(dyn std::ops::Fn(cranelift_codegen::ir::LibCall) -> std::string::String + 'static)>`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0308`.
error: could not compile `rustc_codegen_cranelift`
```

Broken by #2371

### CODE REVIEW

**Review by alexcrichton — APPROVED** [review]
Oops, thanks!

Would it be possible to add this to CI?
