### ISSUE TITLE
Build error with `wasi-c` feature

### ISSUE THREAD

**Issue by dindinw** [bytecodealliance/wasmtime#820]
#### how to reproduce
```
cargo build --all-features --release
```
#### Errors
```
error[E0252]: the name `instantiate_wasi_c` is defined multiple times
  --> src/commands/run.rs:23:5
   |
21 | use wasmtime_wasi_c::instantiate_wasi_c;
   |     ----------------------------------- previous import of the value `instantiate_wasi_c` here
22 | #[cfg(feature = "wasi-c")]
23 | use wasmtime_wasi_c::instantiate_wasi_c;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `instantiate_wasi_c` reimported here
   |
   = note: `instantiate_wasi_c` must be defined only once in the value namespace of this module

warning: unused import: `wasmtime_wasi_c::instantiate_wasi_c`
  --> src/commands/run.rs:23:5
   |
23 | use wasmtime_wasi_c::instantiate_wasi_c;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(unused_imports)]` on by default

error[E0061]: this function takes 5 parameters but 4 parameters were supplied
   --> src/commands/run.rs:155:30
    |
155 |                 let handle = instantiate_wasi_c(global_exports, &preopen_dirs, &argv, &self.vars)?;
    |                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected 5 parameters

error: aborting due to 2 previous errors
```

**Comment by peterhuene** [comment]
Whoops, this looks like it was a bad merge result (there were a lot of merge conflicts prior to landing this file).

I'll get that fixed right now.

**Comment by peterhuene** [comment]
Looks like you beat me to it :)

**Comment by peterhuene** [comment]
@dindinw thanks for the fix!
