### PR TITLE
Convert Souper optimizations to Peepmatic DSL

### PR DESCRIPTION
**Pull request by fitzgen**
Conversion from Souper into Peepmatic is implemented with a straightforward, top-down recursive traversal of the optimization's left- and right-hand side expression DAGs. Most Souper instructions have a corresponding Peepmatic instruction. If we run into an instruction where that isn't the case, we skip that Souper optimization and move on to the next one.

Note that Souper fully supports DAGs, for example:

```text
%0 = var
%1 = add 1, %0
%2 = add %1, %1       ;; Two edges to `%1` makes this a DAG.
```

On the other hand, Peepmatic only currently supports trees, so shared subexpressions are duplicated:

```text
(iadd (iadd 1 $x)
      (iadd 1 $x))    ;; The shared subexpression is duplicated.
```

This does not, however, affect correctness.

See also #2184, which is related.

### CODE REVIEW

**Comment by fitzgen** [comment]
cc @jubitaneja @regehr

File: cranelift/peepmatic/crates/souper/src/lib.rs [hunk 1]
```diff
@@ -0,0 +1,711 @@
...
+        }
+        lhs.push(')');
+        lhs
+    })
+}
+
+fn convert_name(name: &str) -> String {
+    debug_assert!(name.starts_with('%'));
+    debug_assert!(name.len() >= 2);
+    let c = name.chars().nth(1).unwrap();
```
Comment (bjorn3) [inline cranelift/peepmatic/crates/souper/src/lib.rs:118]: You could use `as_bytes()[1]` as `%` is in the ascii range and you are checking if it is an ascii lowercase alphabetic character.

**Comment by fitzgen** [comment]
Looks like this is failing because the `souper-ir` crate uses the `matches!` macro:

```
$ cargo +1.41.0 check -p cranelift-tools
...
error[E0658]: use of unstable library feature 'matches_macro'
   --> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/souper-ir-1.0.0/src/parse.rs:815:24
    |
815 |         let is_block = matches!(assignment.value, ast::AssignmentRhs::Block(_));
    |                        ^^^^^^^
```

@cfallin did Firefox ever update to a newer rustc since we put this check in CI? And if not, does `clif-util` really need to build on rustc 1.41.0? It doesn't get included in Firefox/SpiderMonkey, so I'd expect that the resriction doesn't matter here, like the way it does for `cranelift-codegen`.

If necessary I can also make a new release of `souper-ir` that doesn't use `matches!` but that seems like it shouldn't be necessary.

**Comment by fitzgen** [comment]
TODO: define a `convert_commutative_operation` function to make sure that we canonicalize `iadd`s into `iadd_imm` (etc...) for if either the first or second operand is constant as we convert souper to peepmatic. Right now, a bunch of conversions only check one of the two operands. h/t @jubitaneja

**Comment by jubitaneja** [comment]
Besides the commutative check (mentioned above), it LGTM. Thanks for doing this work, it will also help us use peepmatic.

**Comment by cfallin** [comment]
> @cfallin did Firefox ever update to a newer rustc since we put this check in CI? 

It looks like Firefox's minimum Rust is now 1.43.0 ([link](https://searchfox.org/mozilla-central/rev/eb9d5c97927aea75f0c8e38bbc5b5d288099e687/python/mozboot/mozboot/util.py#16)), so I think we can update the CI check to reflect that (and support `matches!()`). I'll create a PR.

**Comment by cfallin** [comment]
PR: #2193

**Comment by fitzgen** [comment]
> It looks like Firefox's minimum Rust is now 1.43.0 ([link](https://searchfox.org/mozilla-central/rev/eb9d5c97927aea75f0c8e38bbc5b5d288099e687/python/mozboot/mozboot/util.py#16)), so I think we can update the CI check to reflect that (and support `matches!()`). I'll create a PR.

Nice! `matches!` is available in >= 1.42, see the version in the upper right, by the `[src]` link: https://doc.rust-lang.org/nightly/std/macro.matches.html

Thanks for making that PR!

**Review by alexcrichton — APPROVED** [review]
Looks great to me! I'm not super familiar with souper but everything here looks reasonable enough.
