### ISSUE TITLE
feature pooling-allocator doesn't compile on its own

### ISSUE THREAD

**Issue by FrankReh** [bytecodealliance/wasmtime#8889]
Trying to get parts of wasmtime to compile without enlisting all features.

The pooling-allocator feature pulls in some code but uses a field that is only defined when the crate/wasmtime feature "async" is defined.

```
wasmtime $ cargo check --no-default-features --features pooling-allocator
error[E0599]: no method named `total_stacks` found for struct `PoolingAllocationConfig` in the current scope
   --> crates/cli-flags/src/lib.rs:593:29
    |
593 |                         cfg.total_stacks(limit);
    |                             ^^^^^^^^^^^^
    |
```

**Comment by fitzgen** [comment]
Thanks for the bug report -- fix over in https://github.com/bytecodealliance/wasmtime/pull/8891

**Comment by FrankReh** [comment]
Thanks @fitzgen!
