### ISSUE TITLE
fiber: fails to build on 32-bit x86 and arm

### ISSUE THREAD

**Issue by jbeich** [bytecodealliance/wasmtime#7924]
Regresed by #5459 (missed `x86.rs` and `arm.rs`). [Found](https://github.com/bytecodealliance/wasmtime/files/14254571/veloren-weekly-s20240211.log) while [packaging](https://github.com/freebsd/freebsd-ports/commit/76756d2f6d52) [Veloren](https://gitlab.com/veloren/veloren/-/commit/f56e1d84b598).

```rust
$ cargo build --target i686-unknown-linux-gnu
[...]
error[E0432]: unresolved import `wasmtime_asm_macros::asm_sym`
  --> crates/fiber/src/unix/x86.rs:13:37
   |
13 | use wasmtime_asm_macros::{asm_func, asm_sym};
   |                                     ^^^^^^^ no `asm_sym` in the root

For more information about this error, try `rustc --explain E0432`.
error: could not compile `wasmtime-fiber` (lib) due to previous error
```

**Comment by bjorn3** [comment]
Wasmtime doesn't work on 32bit x86 and arm32. It is not just a missing fiber implementation (that would be easy to fix), but also missing backends for both architectures in Cranelift, which is a lot harder to fix. See https://github.com/bytecodealliance/wasmtime/issues/1173 and https://github.com/bytecodealliance/wasmtime/issues/1980.

**Comment by alexcrichton** [comment]
To add more on what @bjorn3 already mentioned, can you clarify what you mean by regressed by #5459? Wasmtime/Cranelift haven't had support for x86 and arm in quite some time so that PR shouldn't have regressed anything "in the large". If, however, you only need the `wasmtime-fiber` crate and nothing else then I can see that PR regressing the support there. Do you only need the `wasmtime-fiber` crate? Given the [commit you linked](https://gitlab.com/veloren/veloren/-/commit/f56e1d84b598) it seems like you're packaging all of Wasmtime so while it doesn't seem like this is the case I wanted to ask to be sure. (if you need all of Wasmtime I'll close this in favor of the issues that @bjorn3 linked tracking 32-bit support)

**Comment by jbeich** [comment]
Indeed. I've got confused by the cruft i.e., `x86` and `arm` support in `wasmtime-fiber` which is trivial to fix by removing unused `asm_sym`. Veloren then failed in `wasmtime-runtime` due to missing assembly but otherwise built fine (I've stubbed the assembly using [x86_64 as example](https://github.com/bytecodealliance/wasmtime/blob/main/crates/runtime/src/arch/x86_64.rs) to check for more errors but didn't find any).
