### PR TITLE
Add TargetIsa::map_dwarf_register; fixes #1471

### LINKED ISSUE #1471: wasmtime fails to compile with could not find `fde` in `isa` within: crates/environ/src/data_structures.rs:18:41 on arm
there's a recent regression in the code: 

```
     Running `rustc --crate-name wasmtime_environ --edition=2018 crates/environ/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C debuginfo=2 -C metadata=3f3bb9806de25bbc -C extra-filename=-3f3bb9806de25bbc --out-dir /tmp/wasmtime/target/armv7-unknown-linux-gnueabihf/debug/deps --target armv7-unknown-linux-gnueabihf -C linker=armv7a-unknown-linux-gnueabihf-gcc -C incremental=/tmp/wasmtime/target/armv7-unknown-linux-gnueabihf/debug/incremental -L dependency=/tmp/wasmtime/target/armv7-unknown-linux-gnueabihf/debug/deps -L dependency=/tmp/wasmtime/target/debug/deps --extern anyhow=/tmp/wasmtime/target/armv7-unknown-linux-gnueabihf/debug/deps/libanyhow-a7d5a95d013f511f.rmeta --extern base64=/tmp/wasmtime/target/armv7-unknown-linux-gnueabihf/debug/deps/libbase64-1fc3337a027c3d46.rmeta --extern bincode=/tmp/wasmtime/target/armv7-unknown-linux-gnueabihf/debug/deps/libbincode-0cfacf3864ed393b.rmeta --extern cranelift_codegen=/tmp/wasmtime/target/armv7-unknown-linux-gnueabihf/debug/deps/libcranelift_codegen-fe4d1e7b8c528231.rmeta --extern cranelift_entity=/tmp/wasmtime/target/armv7-unknown-linux-gnueabihf/debug/deps/libcranelift_entity-6f3c3d46881e39ec.rmeta --extern cranelift_wasm=/tmp/wasmtime/target/armv7-unknown-linux-gnueabihf/debug/deps/libcranelift_wasm-c3fa487d86de75b7.rmeta --extern directories=/tmp/wasmtime/target/armv7-unknown-linux-gnueabihf/debug/deps/libdirectories-32547e134205d970.rmeta --extern errno=/tmp/wasmtime/target/armv7-unknown-linux-gnueabihf/debug/deps/liberrno-aa6b44df9b99329e.rmeta --extern file_per_thread_logger=/tmp/wasmtime/target/armv7-unknown-linux-gnueabihf/debug/deps/libfile_per_thread_logger-c9cdc123d34b0b2e.rmeta --extern indexmap=/tmp/wasmtime/target/armv7-unknown-linux-gnueabihf/debug/deps/libindexmap-062ef480b02be0ea.rmeta --extern libc=/tmp/wasmtime/target/armv7-unknown-linux-gnueabihf/debug/deps/liblibc-45ed8421ceb1d133.rmeta --extern log=/tmp/wasmtime/target/armv7-unknown-linux-gnueabihf/debug/deps/liblog-4ab7a3e889d23791.rmeta --extern more_asserts=/tmp/wasmtime/target/armv7-unknown-linux-gnueabihf/debug/deps/libmore_asserts-4602433f0d9089cb.rmeta --extern rayon=/tmp/wasmtime/target/armv7-unknown-linux-gnueabihf/debug/deps/librayon-8631c1a88fa6e275.rmeta --extern serde=/tmp/wasmtime/target/armv7-unknown-linux-gnueabihf/debug/deps/libserde-198981066e594298.rmeta --extern sha2=/tmp/wasmtime/target/armv7-unknown-linux-gnueabihf/debug/deps/libsha2-39588d910b40a085.rmeta --extern thiserror=/tmp/wasmtime/target/armv7-unknown-linux-gnueabihf/debug/deps/libthiserror-8289a6a6c6a57ad6.rmeta --extern toml=/tmp/wasmtime/target/armv7-unknown-linux-gnueabihf/debug/deps/libtoml-6acf23745dbe4062.rmeta --extern wasmparser=/tmp/wasmtime/target/armv7-unknown-linux-gnueabihf/debug/deps/libwasmparser-6bba5d41f47f7b65.rmeta --extern zstd=/tmp/wasmtime/target/armv7-unknown-linux-gnueabihf/debug/deps/libzstd-4a14a693b151a604.rmeta -L native=/tmp/wasmtime/target/armv7-unknown-linux-gnueabihf/debug/build/zstd-sys-8fe68259522e1833/out`
error[E0432]: unresolved import `cranelift_codegen::isa::fde`
  --> crates/environ/src/data_structures.rs:18:41
   |
18 |         pub use cranelift_codegen::isa::fde::map_reg;
   |                                         ^^^ could not find `fde` in `isa`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0432`.
error: could not compile `wasmtime-environ`.

```

caused by: https://github.com/bytecodealliance/wasmtime/commit/d3df27500334625f463ea0f8134ea28395a5e6a0

reverting the commit locally fixes the issue for me.

### PR DESCRIPTION
**Pull request by abrown**
This exposes the functionality of `fde::map_reg` on the `TargetIsa` trait, avoiding compilation errors on architectures where register mapping is not yet supported. The change is conditially compiled under the `unwind` feature.

### CODE REVIEW

**Comment by abrown** [comment]
@peterhuene, not sure how this will play with #1466 but this does seem like the better long-term solution. Also, I hope my liberal use of `#[cfg(feature = "unwind")]` is what we are looking for here.

**Comment by abrown** [comment]
@stefson, any chance you can try a compile of this branch to see if it actually fixes #1471?

File: cranelift/codegen/src/isa/mod.rs [hunk 1]
```diff
@@ -260,6 +259,12 @@ pub trait TargetIsa: fmt::Display + Send + Sync {
     /// Get a data structure describing the registers in this ISA.
     fn register_info(&self) -> RegInfo;
 
+    #[cfg(feature = "unwind")]
+    /// Map a Cranelift register to its corresponding DWARF register.
+    fn map_dwarf_register(&self, _: RegUnit) -> Result<u16, RegisterMappingError> {
+        return Err(RegisterMappingError::UnsupportedArchitecture);
```
Comment (peterhuene) [inline cranelift/codegen/src/isa/mod.rs:265]: Clippy nit: unnecessary return statement.

**Comment by peterhuene** [comment]
I'll tackle any conflicts this might cause for #1466.

**Comment by yurydelendik** [comment]
> LGTM 👍, but let's get @yurydelendik's opinion as well.

I'm good with the approach.

**Comment by stefson** [comment]
> @stefson, any chance you can try a compile of this branch to see if it actually fixes #1471?

@abrown it seems to depend on an unreleased version of `witx` ?

/tmp/wasmtime $ cargo build --target armv7-unknown-linux-gnueabihf
    Updating crates.io index
error: failed to select a version for the requirement `witx = "^0.8.5"`
  candidate versions found which didn't match: 0.8.4
  location searched: /tmp/wasmtime/crates/wasi-common/WASI/tools/witx
required by package `wig v0.15.0 (/tmp/wasmtime/crates/wasi-common/wig)`

**Comment by abrown** [comment]
@stefson, I see witx at 0.8.5 [available on crates.io](https://crates.io/crates/witx) so I'm not exactly sure what is going on (@pchickey, is it clear to you?). Perhaps there is a `git submodule update` needed when jumping on to this branch?

**Comment by stefson** [comment]
I forgot to update the submodules, I'm sorry :c 

But yes, with your branch it is now back to the old state of an error in wasmtime-obj, where it flakes out with an unsupported platform error, which is expected.
